Repository GauravKarakoti/Weather-API, pull requests merged in 2025-09, with the labels that each got.

#298 refactor: Separate CSS and JS from admin pages
  public/admin/cache.html
  public/admin/dashboard.html
  public/admin/login.html
  public/css/cache.css
  public/css/dashboard.css
  public/css/login.css
  public/js/cache.js
  public/js/dashboard.js
  public/js/login.js
Labels: good first issue, security, gssoc25, level 1, refactor

#266 Added dark and light mode toggle switch to the website
  THEME_IMPLEMENTATION.md
  public/admin/dashboard.html
  public/index.html
  public/theme-manager.js
  public/themes.css
Labels: enhancement, gssoc25, level 2

#315 Added performance.md and documentation.md in the issue template
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/performance.md
Labels: gssoc25, level 1
