Repository GauravKarakoti/Weather-API, pull requests merged in 2025-04, with the labels that each got.

#111 Address Accessibility, Data Parsing, and Error Handling Improvements
  public/index.html
  public/script.js
  server.js
Labels: medium, apertre2.0

#112 Improvements in Weather Display Functionality
  public/script.js
Labels: easy, apertre2.0

#113 solved the bug
  .env.example
  public/script.js
  server.js
Labels: medium, apertre2.0

#118 Update style.css
  public/style.css
Labels: enhancement, easy, apertre2.0

#119 Added favicon to Favicon folder and to index.html
  public/Favicon/Favicon.PNG
  public/index.html
Labels: medium, apertre2.0

#120 UI Enhanced
  public/assets/WeatherBackground.png
  public/index.html
  public/script.js
  public/style.css
Labels: medium, apertre2.0

#122 css selector
  server.js
Labels: medium, apertre2.0

#123 rate limiting
  server.js
Labels: easy, apertre2.0

#124 ineffective rlc
  server.js
  test/server.test.js
Labels: easy, apertre2.0
