Repository GauravKarakoti/Weather-API, pull requests merged in 2025-03, with the labels that each got.

#24 Feat/enhancement
  index.html
  package-lock.json
  script.js
  server.js
  style.css
Labels: hard, apertre2.0

#32 Added MIT License
  Mit License.md
Labels: doc, apertre2.0

#33 Create Security.md
  Security.md
Labels: doc, apertre2.0

#34 Create Code of Conduct.md
  Code of Conduct.md
Labels: doc, apertre2.0

#39 user-friendly messages
  script.js
  server.js
Labels: enhancement, easy, apertre2.0, frontend

#35 ci workflows
  .github/dependabot.yml
  .github/workflows/dependency.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: enhancement, hard, apertre2.0, automation, devops

#42 Dockerize the application
  Dockerfile
  docker-compose.yaml
  public/index.html
  public/script.js
  public/style.css
  server.js
Labels: medium, apertre2.0

#44 integration added
  public/script.js
  server.js
Labels: medium, apertre2.0

#45 Add Unit/Integration Tests
  package-lock.json
  package.json
  public/script.js
  server.js
  test/server.test.js
  test/weather.test.js
Labels: hard, apertre2.0, testing

#49 Unhandled Server Errors for Invalid Cities
  server.js
Labels: bug, backend, medium, apertre2.0

#54 Feat/localstorage fallback
  public/index.html
  public/script.js
Labels: easy, apertre2.0

#55 Update style.css
  public/style.css
Labels: enhancement, easy, apertre2.0

#56 Enhance server error handling and rate limiting features
  server.js
Labels: enhancement, easy, apertre2.0, security, error-handeling, rate-limiting

#61 Feat/backend dead fix
  package.json
  server.js
Labels: easy, apertre2.0

#63 fix No User Feedback for Network Connectivity Issues
  public/script.js
Labels: easy, apertre2.0

#64 Enhanced the features
  public/index.html
  public/script.js
  server.js
Labels: medium, apertre2.0

#65 standardize data units
  server.js
Labels: enhancement, backend, easy, apertre2.0

#66 Improve Data Parsing Reliability and Error Handling
  server.js
Labels: medium, apertre2.0

#84 Update README.md for improved formatting and navigation
  README.md
Labels: doc, apertre2.0

#74 Improve error handling for recent searches in localStorage
  public/script.js
Labels: easy, apertre2.0

#85 Normalize city names in recent searches and update storage logic
  public/script.js
Labels: easy, apertre2.0

#92 Implement service worker for caching and offline support
  public/script.js
  public/sw.js
Labels: medium, apertre2.0

#93 Improve city validation regex to better handle special characters
  server.js
Labels: easy, apertre2.0

#94 Enhance CORS configuration to allow specific origins
  server.js
Labels: easy, apertre2.0

#96 Refactor HTML structure and improve HTML sanitization in script.js
  public/index.html
  public/script.js
Labels: easy, apertre2.0

#102 Fix/backend dead
  .env.example
  public/style.css
  server.js
Labels: medium, apertre2.0

#101 fix Remove client-side temperature parsing duplication
  public/script.js
Labels: easy, apertre2.0

#103 Improve screen reader support for error messages
  public/index.html
  public/script.js
Labels: easy, apertre2.0

#107 fix : Inconsistent Client/Server Input Validation
  public/script.js
Labels: easy, apertre2.0

#108 fix Hardcoded CORS Origins Limit Deployment Flexibility
  .env.example
  server.js
Labels: easy, apertre2.0

#109 Feat/add dynamic search limit
  .env.example
  public/script.js
  server.js
Labels: easy, apertre2.0

#110 Update service worker for dynamic caching and improved error handling
  public/sw.js
Labels: easy, apertre2.0
